// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCS9JtBZlbqncab8B_vqdAp_Dc61Ik0jk',
    appId: '1:783770945837:web:b3808b83de6ec356cb2ba4',
    messagingSenderId: '783770945837',
    projectId: 'beatymaster-82227',
    authDomain: 'beatymaster-82227.firebaseapp.com',
    storageBucket: 'beatymaster-82227.firebasestorage.app',
    measurementId: 'G-KVR0YS1M2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkpTn2k5Ph8AbibJSMnUmYy7Ee26WnJY',
    appId: '1:783770945837:android:3075d5df766004d1cb2ba4',
    messagingSenderId: '783770945837',
    projectId: 'beatymaster-82227',
    storageBucket: 'beatymaster-82227.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxp-Fv638aaSbahgqU7ABxgAKMEDgjwbM',
    appId: '1:783770945837:ios:8c5e8f599b3c1e74cb2ba4',
    messagingSenderId: '783770945837',
    projectId: 'beatymaster-82227',
    storageBucket: 'beatymaster-82227.firebasestorage.app',
    iosBundleId: 'com.fedkru.beautyMaster',
  );
}
